[tool.poetry]
name = "body_part_index"
version = "0.1.0"
description = "Standard anatomic location tags for medical imaging informatics"
authors = ["Tarik Alkasab <tarik.alkasab@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
